### ISSUE TITLE
Running of egamm_22

### ISSUE THREAD

**Issue by jasonaebischerGIT** [wilson-eft/wilson#54] opened 2020-11-25 05:13 UTC
I am getting wrong results when running for example egamm_22 from 60 GeV to 2 GeV. Might be related to a wrong ADM.

**Comment by mdgoodsell** [comment] 2021-06-24 18:34
Has there been any response to this? I find that C7_mumu varies by 48% when I use match_run from the WET at the Z mass to 1 GeV in WET-3, or about the same even just in the WET.

**Comment by DavidMStraub** [comment] 2021-06-24 19:35
What is the actual problem?

**Comment by mdgoodsell** [comment] 2021-06-25 08:19
I'm inputting values for eB_22 and eW_22 in the SMEFT at some scales, then using match_run to run C7_mumu down to 1 GeV (below is not possible). But I can reproduce the problem just in the WET with:

upval=1.0e-5 ### or whatever
my_w = wilson.Wilson({'egamma_22': upval},
                         scale=80.0, eft='WET', basis='JMS')
wc = my_w.match_run(scale=1.0, eft='WET', basis='JMS')
downval=wc['egamma_22'].real
print(downval/upval)

which gives 0.504.

This seems like a huge correction and I was wondering, since there are two open issues about the WET RGEs, if it's correct. If it is correct, then I would also need the running from WET-3 to WET-2 at the muon mass, which match_run says is not implemented yet.

But the running in the SMEFT gives a very small change, and then if I solve by hand using (C.10) from 1711.05270 (just the bit proportional to EM on the first line) then I get a change of about 5%. 

For example, in Mathematica I can run:

Clear[x, y, yin]
e2m0 = 4*Pi/124;
mu0 = 90;
b0 = -4/3*(ne + 1/3*nd + 4/3*nu) /. {ne -> 3, nd -> 3, nu -> 2};
e2[mu_] := e2m0/(1 + 2 b0*e2m0/(16*Pi^2)*Log[mu/mu0])
yin = 1; (* OR whatever, although Mathematica has numerical problems with small values below about 10^(-6) *)
ss = 
 NDSolve[{y'[x] == (10 - b0)*e2[x]*y[x]/x/(16*Pi^2), y[mu0] == yin}, 
   y, {x, mu0, 0.2}][[1]]
(y[1]/.ss)/yin

gives a ratio of 94.8% of the inital value. Of course the above can be solved exactly. So I don't understand the result from Wilson unless I am being naive and there is another effect that I have forgotten about in my simplistic calculation.

**Comment by jasonaebischerGIT** [comment] 2021-06-29 16:56
Hi @mdgoodsell ,
thanks a lot for your comment and explanation! I experienced similar problems but have not found the reason for it yet. 
I will have a closer look into it.

**Comment by jasonaebischerGIT** [comment] 2021-08-07 09:17
I am not sure anymore why we scale the dipole operators with the scale_C function in wet/rge.py, L103. Could the problem come form there?
At some point we decided to normalize these operators with these different normalizations, but now I am not sure if that is correct...

**Comment by DavidMStraub** [comment] 2021-08-07 09:35
I think it's to be able to use the analytical RGE solution formulas from AFGV when using the JMS basis instead of Bern as input. I am pretty sure we checked the old (Bern) implementation of WETrunner vs. the new one (based on JMS) at one loop, so it would be very surprising if there were a bug in there. It must be something specific to the leptonic dipole (which was not there in Bern).

**Comment by jasonaebischerGIT** [comment] 2021-08-07 09:46
Thanks @DavidMStraub , I think you are right. I remember that we normalized the dipoles in this way such that they are formally at the same order as the four-quark ones. I will still have another look whether everything is fine there, but most probably the issue lies in the leptonic ones.

**Comment by fionq** [comment] 2021-09-28 10:41
Hi! Same issue here:
`
from wilson import Wilson
WilsonInst = Wilson({'Cgamma_mue': 1}, scale=100, eft='WET', basis='flavio')
wc = WilsonInst.match_run(scale=1, eft='WET', basis='flavio')
wc
`
returns 0.493866 at the low scale. This jump happens in scale_C of wilson/run/wet/rge.py.

**Comment by jasonaebischerGIT** [comment] 2021-10-08 14:50
I am confused about the order of the operators in the ADMs adm_s_dF0 and adm_e_dF0 in L2027 and L1701 of run/wet/adm.py. Is it the same as suggested on p. 35 of https://wcxf.github.io/assets/pdf/WET.JMS.pdf ? Because then the egamma_22 would have a QCD but no QED running....

**Comment by jasonaebischerGIT** [comment] 2021-10-08 15:18
> For reference, the order for `dF=0` is
> 
> ```json
> [
>     "G",
>     "Gtilde",
>     "S1ddRR_1111",
>     "S1ddRR_1122",
>     "S1ddRR_1133",
>     "S1ddRR_1221",
>     "S1ddRR_1331",
>     "S1ddRR_2222",
>     "S1ddRR_2233",
>     "S1ddRR_2332",
>     "S1ddRR_3333",
>     "S1udRR_1111",
>     "S1udRR_1122",
>     "S1udRR_1133",
>     "S1udRR_2211",
>     "S1udRR_2222",
>     "S1udRR_2233",
>     "S1udduRR_1111",
>     "S1udduRR_1221",
>     "S1udduRR_1331",
>     "S1udduRR_2112",
>     "S1udduRR_2222",
>     "S1udduRR_2332",
>     "S1uuRR_1111",
>     "S1uuRR_1122",
>     "S1uuRR_1221",
>     "S1uuRR_2222",
>     "S8ddRR_1111",
>     "S8ddRR_1122",
>     "S8ddRR_1133",
>     "S8ddRR_1221",
>     "S8ddRR_1331",
>     "S8ddRR_2222",
>     "S8ddRR_2233",
>     "S8ddRR_2332",
>     "S8ddRR_3333",
>     "S8udRR_1111",
>     "S8udRR_1122",
>     "S8udRR_1133",
>     "S8udRR_2211",
>     "S8udRR_2222",
>     "S8udRR_2233",
>     "S8udduRR_1111",
>     "S8udduRR_1221",
>     "S8udduRR_1331",
>     "S8udduRR_2112",
>     "S8udduRR_2222",
>     "S8udduRR_2332",
>     "S8uuRR_1111",
>     "S8uuRR_1122",
>     "S8uuRR_1221",
>     "S8uuRR_2222",
>     "SedRL_1111",
>     "SedRL_1122",
>     "SedRL_1133",
>     "SedRL_2211",
>     "SedRL_2222",
>     "SedRL_2233",
>     "SedRL_3311",
>     "SedRL_3322",
>     "SedRL_3333",
>     "SedRR_1111",
>     "SedRR_1122",
>     "SedRR_1133",
>     "SedRR_2211",
>     "SedRR_2222",
>     "SedRR_2233",
>     "SedRR_3311",
>     "SedRR_3322",
>     "SedRR_3333",
>     "SeeRR_1111",
>     "SeeRR_1122",
>     "SeeRR_1133",
>     "SeeRR_1221",
>     "SeeRR_1331",
>     "SeeRR_2222",
>     "SeeRR_2233",
>     "SeeRR_2332",
>     "SeeRR_3333",
>     "SeuRL_1111",
>     "SeuRL_1122",
>     "SeuRL_2211",
>     "SeuRL_2222",
>     "SeuRL_3311",
>     "SeuRL_3322",
>     "SeuRR_1111",
>     "SeuRR_1122",
>     "SeuRR_2211",
>     "SeuRR_2222",
>     "SeuRR_3311",
>     "SeuRR_3322",
>     "TedRR_1111",
>     "TedRR_1122",
>     "TedRR_1133",
>     "TedRR_2211",
>     "TedRR_2222",
>     "TedRR_2233",
>     "TedRR_3311",
>     "TedRR_3322",
>     "TedRR_3333",
>     "TeuRR_1111",
>     "TeuRR_1122",
>     "TeuRR_2211",
>     "TeuRR_2222",
>     "TeuRR_3311",
>     "TeuRR_3322",
>     "V1ddLR_1111",
>     "V1ddLR_1122",
>     "V1ddLR_1133",
>     "V1ddLR_1221",
>     "V1ddLR_1331",
>     "V1ddLR_2211",
>     "V1ddLR_2222",
>     "V1ddLR_2233",
>     "V1ddLR_2332",
>     "V1ddLR_3311",
>     "V1ddLR_3322",
>     "V1ddLR_3333",
>     "V1duLR_1111",
>     "V1duLR_1122",
>     "V1duLR_2211",
>     "V1duLR_2222",
>     "V1duLR_3311",
>     "V1duLR_3322",
>     "V1udLL_1111",
>     "V1udLL_1122",
>     "V1udLL_1133",
>     "V1udLL_2211",
>     "V1udLL_2222",
>     "V1udLL_2233",
>     "V1udLR_1111",
>     "V1udLR_1122",
>     "V1udLR_1133",
>     "V1udLR_2211",
>     "V1udLR_2222",
>     "V1udLR_2233",
>     "V1udRR_1111",
>     "V1udRR_1122",
>     "V1udRR_1133",
>     "V1udRR_2211",
>     "V1udRR_2222",
>     "V1udRR_2233",
>     "V1udduLR_1111",
>     "V1udduLR_1221",
>     "V1udduLR_1331",
>     "V1udduLR_2112",
>     "V1udduLR_2222",
>     "V1udduLR_2332",
>     "V1uuLR_1111",
>     "V1uuLR_1122",
>     "V1uuLR_1221",
>     "V1uuLR_2211",
>     "V1uuLR_2222",
>     "V8ddLR_1111",
>     "V8ddLR_1122",
>     "V8ddLR_1133",
>     "V8ddLR_1221",
>     "V8ddLR_1331",
>     "V8ddLR_2211",
>     "V8ddLR_2222",
>     "V8ddLR_2233",
>     "V8ddLR_2332",
>     "V8ddLR_3311",
>     "V8ddLR_3322",
>     "V8ddLR_3333",
>     "V8duLR_1111",
>     "V8duLR_1122",
>     "V8duLR_2211",
>     "V8duLR_2222",
>     "V8duLR_3311",
>     "V8duLR_3322",
>     "V8udLL_1111",
>     "V8udLL_1122",
>     "V8udLL_1133",
>     "V8udLL_2211",
>     "V8udLL_2222",
>     "V8udLL_2233",
>     "V8udLR_1111",
>     "V8udLR_1122",
>     "V8udLR_1133",
>     "V8udLR_2211",
>     "V8udLR_2222",
>     "V8udLR_2233",
>     "V8udRR_1111",
>     "V8udRR_1122",
>     "V8udRR_1133",
>     "V8udRR_2211",
>     "V8udRR_2222",
>     "V8udRR_2233",
>     "V8udduLR_1111",
>     "V8udduLR_1221",
>     "V8udduLR_1331",
>     "V8udduLR_2112",
>     "V8udduLR_2222",
>     "V8udduLR_2332",
>     "V8uuLR_1111",
>     "V8uuLR_1122",
>     "V8uuLR_1221",
>     "V8uuLR_2211",
>     "V8uuLR_2222",
>     "VddLL_1111",
>     "VddLL_1122",
>     "VddLL_1133",
>     "VddLL_1221",
>     "VddLL_1331",
>     "VddLL_2222",
>     "VddLL_2233",
>     "VddLL_2332",
>     "VddLL_3333",
>     "VddRR_1111",
>     "VddRR_1122",
>     "VddRR_1133",
>     "VddRR_1221",
>     "VddRR_1331",
>     "VddRR_2222",
>     "VddRR_2233",
>     "VddRR_2332",
>     "VddRR_3333",
>     "VdeLR_1111",
>     "VdeLR_1122",
>     "VdeLR_1133",
>     "VdeLR_2211",
>     "VdeLR_2222",
>     "VdeLR_2233",
>     "VdeLR_3311",
>     "VdeLR_3322",
>     "VdeLR_3333",
>     "VedLL_1111",
>     "VedLL_1122",
>     "VedLL_1133",
>     "VedLL_2211",
>     "VedLL_2222",
>     "VedLL_2233",
>     "VedLL_3311",
>     "VedLL_3322",
>     "VedLL_3333",
>     "VedLR_1111",
>     "VedLR_1122",
>     "VedLR_1133",
>     "VedLR_2211",
>     "VedLR_2222",
>     "VedLR_2233",
>     "VedLR_3311",
>     "VedLR_3322",
>     "VedLR_3333",
>     "VedRR_1111",
>     "VedRR_1122",
>     "VedRR_1133",
>     "VedRR_2211",
>     "VedRR_2222",
>     "VedRR_2233",
>     "VedRR_3311",
>     "VedRR_3322",
>     "VedRR_3333",
>     "VeeLL_1111",
>     "VeeLL_1122",
>     "VeeLL_1133",
>     "VeeLL_2222",
>     "VeeLL_2233",
>     "VeeLL_3333",
>     "VeeLR_1111",
>     "VeeLR_1122",
>     "VeeLR_1133",
>     "VeeLR_1221",
>     "VeeLR_1331",
>     "VeeLR_2211",
>     "VeeLR_2222",
>     "VeeLR_2233",
>     "VeeLR_2332",
>     "VeeLR_3311",
>     "VeeLR_3322",
>     "VeeLR_3333",
>     "VeeRR_1111",
>     "VeeRR_1122",
>     "VeeRR_1133",
>     "VeeRR_2222",
>     "VeeRR_2233",
>     "VeeRR_3333",
>     "VeuLL_1111",
>     "VeuLL_1122",
>     "VeuLL_2211",
>     "VeuLL_2222",
>     "VeuLL_3311",
>     "VeuLL_3322",
>     "VeuLR_1111",
>     "VeuLR_1122",
>     "VeuLR_2211",
>     "VeuLR_2222",
>     "VeuLR_3311",
>     "VeuLR_3322",
>     "VeuRR_1111",
>     "VeuRR_1122",
>     "VeuRR_2211",
>     "VeuRR_2222",
>     "VeuRR_3311",
>     "VeuRR_3322",
>     "VueLR_1111",
>     "VueLR_1122",
>     "VueLR_1133",
>     "VueLR_2211",
>     "VueLR_2222",
>     "VueLR_2233",
>     "VuuLL_1111",
>     "VuuLL_1122",
>     "VuuLL_1221",
>     "VuuLL_2222",
>     "VuuRR_1111",
>     "VuuRR_1122",
>     "VuuRR_1221",
>     "VuuRR_2222",
>     "dG_11",
>     "dG_22",
>     "dG_33",
>     "dgamma_11",
>     "dgamma_22",
>     "dgamma_33",
>     "egamma_11",
>     "egamma_22",
>     "egamma_33",
>     "uG_11",
>     "uG_22",
>     "ugamma_11",
>     "ugamma_22"
> ]
> ```

thanks a lot. Let me check!

**Comment by DavidMStraub** [comment] 2021-10-09 07:04
Yes, JMS

**Comment by jackypheno** [comment] 2021-11-02 16:06
@jasonaebischerGIT @DavidMStraub  Two things:

First I confirm that the (317,317) entry in adm_s_dF0 is non-zero which looks like an error. But even if I set this entry to zero, the problem seems to persist!

Second, I am confused why leptonic Wilson coefficients are rescaled by g^2/e/m?  In Bern basis, this scaling was used for the quark dipole operators. Playing with this scaling, e.g. setting it to  e/m  instead of g^2/e/m for the leptonic dipoles seems to solve the problem provided that QCD ADMs are also fixed.

**Comment by jasonaebischerGIT** [comment] 2021-11-18 08:57
@jackypheno Yes, I agree. Switching off the QCD ADM and removing g**2 leads to the correct result.
Let's look at the ADM next.

**Comment by mdgoodsell** [comment] 2022-02-09 10:58
So is this issue fixed or close to being fixed now? I haven't seen an update to the public code, but maybe this:

https://github.com/wilson-eft/wilson/pull/92

is related and you are working on it?

**Comment by jackypheno** [comment] 2022-02-09 11:26
@mdgoodsell Yes its work in progress. We in process of implementing a brand new LEFT beta functions and their solutions based on https://arxiv.org/abs/1711.05270. Yes its partly related to #92  as well.

**Comment by peterstangl** [comment] 2022-06-11 13:06
This issue has been fixed in PR #97. The bug fix is included in wilson v2.3.

**Closed by peterstangl** 2022-06-11 13:06 UTC
Labels: bug
