### ISSUE TITLE
Sign flip in Wilson coefficient

### ISSUE THREAD

**Issue by fionq** [wilson-eft/wilson#74] opened 2021-07-28 11:33 UTC
Dear authors of wilson,

I was computing the running of the operator 'phil1_12', when I noticed that the sign of the Wilson coefficient flips.
Here's a minimal code that reproduces the issue:

```python
import wilson

WChigh = wilson.Wilson({'phil1_12': 1e-6}, scale=100.01, eft='SMEFT', basis='Warsaw')
WClow = WChigh.match_run(scale=100, eft='SMEFT', basis='Warsaw')
WClow['phil1_12']
```

For C_in['phil1_12'] = 1e-6, I find C_out['phil1_12'] = -9.99996428366162e-07, which seems plausible, up to the sign.

I suspect this sign flip originates in a small imaginary part, which is introduced by the "flavour rotation":

https://github.com/wilson-eft/wilson/blob/503c85fb6bbdbfbb2c5462854126375143cfc541/wilson/run/smeft/classes.py#L125-L142

(The issue can be alleviated by taking the real part of Mep, however, this is not really a solution...) 

It may well be, however, that I am not using the code properly. What do you think? 
Any feedback would be much appreciated. Many thanks!

**Comment by peterstangl** [comment] 2021-07-29 12:13
This issue looks like a duplicate of issue #63.

**Comment by DavidMStraub** [comment] 2021-07-29 13:11
Thanks for noticing @peterstangl, was about to explain the same thing 😉 IMO can be closed as duplicate.

**Comment by jasonaebischerGIT** [comment] 2021-07-29 13:24
Yes, I agree. Thanks @peterstangl !

**Comment by fionq** [comment] 2021-07-29 16:39
Ah thanks, hadn't spotted that one.

**Closed** 2021-07-29 16:46 UTC
